#!/bin/bash
echo ''
echo '⚙️  Provider Configuration'
echo '═══════════════════════════════════════════════════════════════'
echo ''
echo '✅ AVAILABLE WITHOUT API KEYS:'
echo '   • Apple Health - Sync via iOS app (no API key needed)'
echo ''
echo '🔐 REQUIRE DEVELOPER API ACCESS (Business accounts only):'
echo '   • Garmin  - Requires Garmin Health API partnership'
echo '   • Suunto  - Requires Suunto API partnership'
echo '   • Polar   - Requires Polar AccessLink API access'
echo '   • Whoop   - Requires Whoop API access'
echo ''
echo '📝 To configure providers with API keys:'
echo '   1. Edit: backend/config/.env.local'
echo '   2. Add your CLIENT_ID and CLIENT_SECRET for each provider'
echo '   3. Restart Open Wearables (Stop → Start)'
echo ''
echo '💡 For personal use, Apple Health covers most fitness data!'
echo ''

