#!/bin/bash
echo '📋 Open Wearables Logs (last 50 lines per service)'
echo ''
echo '═══════════════════════════════════════════════════════════════'
echo '🔧 BACKEND LOGS:'
docker logs owlocal-backend --tail 50 2>&1 || echo 'Backend not running'
echo ''
echo '═══════════════════════════════════════════════════════════════'
echo '🎨 FRONTEND LOGS:'
docker logs owlocal-frontend --tail 30 2>&1 || echo 'Frontend not running'
echo ''
echo '═══════════════════════════════════════════════════════════════'
echo '⚙️  WORKER LOGS:'
docker logs owlocal-worker --tail 20 2>&1 || echo 'Worker not running'
echo ''
echo '═══════════════════════════════════════════════════════════════'
echo '📊 CONTAINER STATUS:'
docker ps -a --filter 'name=owlocal' --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'

