# Changes here will be overwritten by Copier
_commit: 0.3.0
_src_path: https://github.com/the-momentum/python-ai-kit
default_python_version: '3.13'
plugins:
- celery
- sentry
project_description: ''
project_name: open-wearables
project_type: api-microservice
python_versions:
- '3.13'
- '3.14'
