"""common workout model

Revision ID: 1d860e21ae43
Revises: 888e359b8ac9

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d860e21ae43'
down_revision: Union[str, None] = '888e359b8ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sourceName', sa.String(length=100), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadataentry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workoutstatistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workout', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('workout', sa.Column('durationUnit', sa.String(length=10), nullable=False))
    op.add_column('workout', sa.Column('sourceName', sa.String(length=100), nullable=False))
    op.add_column('workout', sa.Column('startDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('workout', sa.Column('endDate', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('workout', 'duration',
               existing_type=sa.NUMERIC(precision=15, scale=5),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.drop_column('workout', 'active_energy_burned_qty')
    op.drop_column('workout', 'humidity_units')
    op.drop_column('workout', 'intensity_qty')
    op.drop_column('workout', 'intensity_units')
    op.drop_column('workout', 'temperature_units')
    op.drop_column('workout', 'distance_qty')
    op.drop_column('workout', 'start')
    op.drop_column('workout', 'humidity_qty')
    op.drop_column('workout', 'end')
    op.drop_column('workout', 'active_energy_burned_units')
    op.drop_column('workout', 'distance_units')
    op.drop_column('workout', 'location')
    op.drop_column('workout', 'name')
    op.drop_column('workout', 'temperature_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('temperature_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('distance_units', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('active_energy_burned_units', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('humidity_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('distance_qty', sa.NUMERIC(precision=15, scale=5), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('temperature_units', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('intensity_units', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('intensity_qty', sa.NUMERIC(precision=15, scale=5), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('humidity_units', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('active_energy_burned_qty', sa.NUMERIC(precision=15, scale=5), autoincrement=False, nullable=True))
    op.alter_column('workout', 'duration',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=5),
               nullable=True)
    op.drop_column('workout', 'endDate')
    op.drop_column('workout', 'startDate')
    op.drop_column('workout', 'sourceName')
    op.drop_column('workout', 'durationUnit')
    op.drop_column('workout', 'type')
    op.drop_table('workoutstatistic')
    op.drop_table('metadataentry')
    op.drop_table('record')
    # ### end Alembic commands ###
