"""common record model

Revision ID: 624a2c993a26
Revises: 0499653ca8ea

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624a2c993a26'
down_revision: Union[str, None] = '0499653ca8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.alter_column('record', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('record', 'sourceName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'sourceName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('record', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('record', 'provider_id')
    # ### end Alembic commands ###
