"""common record model

Revision ID: 703a9e4c2a46
Revises: 624a2c993a26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '703a9e4c2a46'
down_revision: Union[str, None] = '624a2c993a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'sourceName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('workout', 'duration',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('workout', 'durationUnit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('workout', 'sourceName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('workout', 'startDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('workout', 'endDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'endDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('workout', 'startDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('workout', 'sourceName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('workout', 'durationUnit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('workout', 'duration',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('record', 'sourceName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
