"""add_user_connections_table

Revision ID: bb3d1c8232ec
Revises: 907ae6e7b787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb3d1c8232ec"
down_revision: Union[str, None] = "907ae6e7b787"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userconnection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_user_id", sa.Text(), nullable=True),
        sa.Column("provider_username", sa.Text(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_provider"),
    )
    op.create_index(
        "idx_user_connections_token_expiry",
        "userconnection",
        ["token_expires_at"],
        unique=False,
        postgresql_where="status = 'active'",
    )
    op.create_index("idx_user_connections_user_provider", "userconnection", ["user_id", "provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_connections_user_provider", table_name="userconnection")
    op.drop_index(
        "idx_user_connections_token_expiry", table_name="userconnection", postgresql_where="status = 'active'"
    )
    op.drop_table("userconnection")
    # ### end Alembic commands ###
