/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetConnectRouteImport } from './routes/widget.connect'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as UsersUserIdPairRouteImport } from './routes/users/$userId/pair'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as UsersUserIdPairIndexRouteImport } from './routes/users/$userId/pair.index'
import { Route as UsersUserIdPairSuccessRouteImport } from './routes/users/$userId/pair.success'
import { Route as UsersUserIdPairErrorRouteImport } from './routes/users/$userId/pair.error'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetConnectRoute = WidgetConnectRouteImport.update({
  id: '/widget/connect',
  path: '/widget/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const UsersUserIdPairRoute = UsersUserIdPairRouteImport.update({
  id: '/users/$userId/pair',
  path: '/users/$userId/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const UsersUserIdPairIndexRoute = UsersUserIdPairIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const UsersUserIdPairSuccessRoute = UsersUserIdPairSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const UsersUserIdPairErrorRoute = UsersUserIdPairErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/widget/connect': typeof WidgetConnectRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/$userId/pair': typeof UsersUserIdPairRouteWithChildren
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/users/$userId/pair/': typeof UsersUserIdPairIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/widget/connect': typeof WidgetConnectRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/users/$userId/pair': typeof UsersUserIdPairIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/widget/connect': typeof WidgetConnectRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/$userId/pair': typeof UsersUserIdPairRouteWithChildren
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/users/$userId/pair/': typeof UsersUserIdPairIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/widget/connect'
    | '/users/$userId'
    | '/users/$userId/pair'
    | '/users/'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/users/$userId/pair/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/widget/connect'
    | '/users/$userId'
    | '/users'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/users/$userId/pair'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/widget/connect'
    | '/_authenticated/users/$userId'
    | '/users/$userId/pair'
    | '/_authenticated/users/'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/users/$userId/pair/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WidgetConnectRoute: typeof WidgetConnectRoute
  UsersUserIdPairRoute: typeof UsersUserIdPairRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/connect': {
      id: '/widget/connect'
      path: '/widget/connect'
      fullPath: '/widget/connect'
      preLoaderRoute: typeof WidgetConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/users/$userId/pair': {
      id: '/users/$userId/pair'
      path: '/users/$userId/pair'
      fullPath: '/users/$userId/pair'
      preLoaderRoute: typeof UsersUserIdPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/users/$userId/pair/': {
      id: '/users/$userId/pair/'
      path: '/'
      fullPath: '/users/$userId/pair/'
      preLoaderRoute: typeof UsersUserIdPairIndexRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/users/$userId/pair/success': {
      id: '/users/$userId/pair/success'
      path: '/success'
      fullPath: '/users/$userId/pair/success'
      preLoaderRoute: typeof UsersUserIdPairSuccessRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/users/$userId/pair/error': {
      id: '/users/$userId/pair/error'
      path: '/error'
      fullPath: '/users/$userId/pair/error'
      preLoaderRoute: typeof UsersUserIdPairErrorRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
  }
}

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UsersUserIdPairRouteChildren {
  UsersUserIdPairErrorRoute: typeof UsersUserIdPairErrorRoute
  UsersUserIdPairSuccessRoute: typeof UsersUserIdPairSuccessRoute
  UsersUserIdPairIndexRoute: typeof UsersUserIdPairIndexRoute
}

const UsersUserIdPairRouteChildren: UsersUserIdPairRouteChildren = {
  UsersUserIdPairErrorRoute: UsersUserIdPairErrorRoute,
  UsersUserIdPairSuccessRoute: UsersUserIdPairSuccessRoute,
  UsersUserIdPairIndexRoute: UsersUserIdPairIndexRoute,
}

const UsersUserIdPairRouteWithChildren = UsersUserIdPairRoute._addFileChildren(
  UsersUserIdPairRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WidgetConnectRoute: WidgetConnectRoute,
  UsersUserIdPairRoute: UsersUserIdPairRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
