"""external_provider_user_id_index

Revision ID: 5aaff4551af6
Revises: d8a0bc9afdd9

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5aaff4551af6"
down_revision: Union[str, None] = "d8a0bc9afdd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_connection_provider_external_id",
        "user_connection",
        ["provider", "provider_user_id"],
        unique=False,
        postgresql_where="provider_user_id IS NOT NULL AND status = 'active'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_connection_provider_external_id",
        table_name="user_connection",
        postgresql_where="provider_user_id IS NOT NULL AND status = 'active'",
    )
    # ### end Alembic commands ###
