"""webhook secret setting

Revision ID: 6b11080054a0
Revises: d15dee848b33

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b11080054a0"
down_revision: Union[str, None] = "d15dee848b33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider_settings", sa.Column("webhook_secret", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_settings", "webhook_secret")
    # ### end Alembic commands ###
