"""align enum column types with type annotation map

Revision ID: 11552dbe45d3
Revises: d8a0bc9afdd9

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11552dbe45d3"
down_revision: Union[str, None] = "d8a0bc9afdd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted: the native enum stored member names ("WATCH") while
    # data_source.device_type stores StrEnum values ("watch"), so convert to
    # lowercase values and drop the now-unused devicetype type.
    op.alter_column(
        "device_type_priority",
        "device_type",
        existing_type=postgresql.ENUM("WATCH", "BAND", "PHONE", "SCALE", "RING", "OTHER", "UNKNOWN", name="devicetype"),
        type_=sa.String(length=32),
        postgresql_using="lower(device_type::text)",
        existing_nullable=False,
    )
    op.execute("DROP TYPE devicetype")
    op.alter_column(
        "provider_settings",
        "provider",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "user_connection",
        "provider",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_connection",
        "provider",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "provider_settings",
        "provider",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    devicetype = postgresql.ENUM("WATCH", "BAND", "PHONE", "SCALE", "RING", "OTHER", "UNKNOWN", name="devicetype")
    devicetype.create(op.get_bind())
    op.alter_column(
        "device_type_priority",
        "device_type",
        existing_type=sa.String(length=32),
        type_=devicetype,
        postgresql_using="upper(device_type)::devicetype",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
