"""health score fk rename

Revision ID: dc5ac28c4b94
Revises: b2c3d4e5f6a1

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5ac28c4b94'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_score', sa.Column('event_record_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('uq_health_score_sleep_record'), table_name='health_score', postgresql_where='(sleep_record_id IS NOT NULL)')
    op.create_index('uq_health_score_event_record', 'health_score', ['event_record_id'], unique=True, postgresql_where=sa.text('event_record_id IS NOT NULL'))
    op.drop_constraint(op.f('health_score_sleep_record_id_fkey'), 'health_score', type_='foreignkey')
    op.create_foreign_key(None, 'health_score', 'event_record', ['event_record_id'], ['id'], ondelete='CASCADE')
    op.drop_column('health_score', 'sleep_record_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_score', sa.Column('sleep_record_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'health_score', type_='foreignkey')
    op.create_foreign_key(op.f('health_score_sleep_record_id_fkey'), 'health_score', 'event_record', ['sleep_record_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_health_score_event_record', table_name='health_score', postgresql_where=sa.text('event_record_id IS NOT NULL'))
    op.create_index(op.f('uq_health_score_sleep_record'), 'health_score', ['sleep_record_id'], unique=True, postgresql_where='(sleep_record_id IS NOT NULL)')
    op.drop_column('health_score', 'event_record_id')
    # ### end Alembic commands ###
