"""data source stable identity

Revision ID: 2a52f24a8ccf
Revises: a18e054b6e0f

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a52f24a8ccf"
down_revision: Union[str, None] = "a18e054b6e0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LEGACY_IDENTITY = [
    "user_id",
    "provider",
    sa.literal_column("COALESCE(device_model, '')"),
    sa.literal_column("COALESCE(source, '')"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_source", sa.Column("device_id", sa.String(length=100), nullable=True))
    op.add_column("data_source", sa.Column("source_app_id", sa.String(length=100), nullable=True))
    op.add_column("data_source", sa.Column("device_manufacturer", sa.String(length=100), nullable=True))
    op.create_index(
        "uq_data_source_app",
        "data_source",
        ["user_id", "provider", "source_app_id", sa.literal_column("COALESCE(device_model, '')")],
        unique=True,
        postgresql_where=sa.text("device_id IS NULL AND source_app_id IS NOT NULL"),
    )
    op.create_index(
        "uq_data_source_device",
        "data_source",
        ["user_id", "provider", "device_id"],
        unique=True,
        postgresql_where=sa.text("device_id IS NOT NULL"),
    )
    # ### end Alembic commands ###
    # Autogenerate misses postgresql_where changes: the legacy identity only applies without stable ids
    op.drop_index("uq_data_source_identity", table_name="data_source")
    op.create_index(
        "uq_data_source_identity",
        "data_source",
        LEGACY_IDENTITY,
        unique=True,
        postgresql_where=sa.text("device_id IS NULL AND source_app_id IS NULL"),
    )


def downgrade() -> None:
    # Rows told apart only by their stable ids collide under the legacy identity; keep them apart by source
    op.execute("""
        UPDATE data_source d SET source = left(coalesce(d.source, ''), 90) || ' #' || left(d.id::text, 8)
        WHERE (d.device_id IS NOT NULL OR d.source_app_id IS NOT NULL)
          AND EXISTS (
              SELECT 1 FROM data_source o
              WHERE o.id <> d.id AND o.user_id = d.user_id AND o.provider = d.provider
                AND coalesce(o.device_model, '') = coalesce(d.device_model, '')
                AND coalesce(o.source, '') = coalesce(d.source, '')
          )
    """)
    op.drop_index("uq_data_source_identity", table_name="data_source")
    op.create_index("uq_data_source_identity", "data_source", LEGACY_IDENTITY, unique=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_data_source_device", table_name="data_source", postgresql_where=sa.text("device_id IS NOT NULL"))
    op.drop_index(
        "uq_data_source_app",
        table_name="data_source",
        postgresql_where=sa.text("device_id IS NULL AND source_app_id IS NOT NULL"),
    )
    op.drop_column("data_source", "device_manufacturer")
    op.drop_column("data_source", "source_app_id")
    op.drop_column("data_source", "device_id")
    # ### end Alembic commands ###
