"""meal correlation support and nutrition series types

Revision ID: 1eb31a2ae822
Revises: a18e054b6e0f

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1eb31a2ae822"
down_revision: Union[str, None] = "a18e054b6e0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Keep in sync with SERIES_TYPE_DEFINITIONS in app/schemas/enums/series_types.py -
# these 4 rows are the ones scripts/init/seed_series_types.py would otherwise only add
# the next time it's run by hand.
NEW_SERIES_TYPES = [
    (298, "dietary_fat_trans", "g"),
    (299, "dietary_energy_from_fat", "kcal"),
    (300, "dietary_fat_unsaturated", "g"),
    (301, "dietary_folic_acid", "mcg"),
]

series_type_definition = sa.table(
    "series_type_definition",
    sa.column("id", sa.Integer),
    sa.column("code", sa.String),
    sa.column("unit", sa.String),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_details",
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("meal_type", sa.String(length=32), nullable=True),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["record_id"], ["event_record.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.add_column("data_point_series", sa.Column("event_record_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "data_point_series_event_record_id_fkey",
        "data_point_series",
        "event_record",
        ["event_record_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_event_record_meal_source_external_id",
        "event_record",
        ["data_source_id", "external_id"],
        unique=True,
        postgresql_where="category = 'meal'",
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        series_type_definition,
        [{"id": type_id, "code": code, "unit": unit} for type_id, code, unit in NEW_SERIES_TYPES],
    )


def downgrade() -> None:
    op.execute(
        series_type_definition.delete().where(
            series_type_definition.c.id.in_([type_id for type_id, _, _ in NEW_SERIES_TYPES])
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_event_record_meal_source_external_id", table_name="event_record", postgresql_where="category = 'meal'"
    )
    op.drop_constraint("data_point_series_event_record_id_fkey", "data_point_series", type_="foreignkey")
    op.drop_column("data_point_series", "event_record_id")
    op.drop_table("meal_details")
    # ### end Alembic commands ###
