"""sync run tracking

Revision ID: 2fadb2c02fc0
Revises: b2c3d4e5f6a1

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fadb2c02fc0'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_inserted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_key')
    )
    op.create_index('ix_sync_run_in_progress', 'sync_run', ['started_at'], unique=False, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_index('ix_sync_run_provider_status', 'sync_run', ['provider', 'status'], unique=False)
    op.create_index('ix_sync_run_user_started_at', 'sync_run', ['user_id', 'started_at'], unique=False)
    op.create_table('sync_run_data_type',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('native_type', sa.String(length=100), nullable=True),
    sa.Column('reported_records', sa.Integer(), nullable=True),
    sa.Column('items_inserted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('covered_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('covered_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['sync_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'data_type')
    )
    op.create_index('ix_sync_run_data_type_type_status', 'sync_run_data_type', ['data_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_run_data_type_type_status', table_name='sync_run_data_type')
    op.drop_table('sync_run_data_type')
    op.drop_index('ix_sync_run_user_started_at', table_name='sync_run')
    op.drop_index('ix_sync_run_provider_status', table_name='sync_run')
    op.drop_index('ix_sync_run_in_progress', table_name='sync_run', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_table('sync_run')
    # ### end Alembic commands ###
