"""zone_offset

Revision ID: 1c406c92dfee
Revises: 07afc893962c

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c406c92dfee'
down_revision: Union[str, None] = '07afc893962c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_point_series', sa.Column('zone_offset', sa.String(length=10), nullable=True))
    op.add_column('event_record', sa.Column('zone_offset', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_record', 'zone_offset')
    op.drop_column('data_point_series', 'zone_offset')
    # ### end Alembic commands ###
