"""parse additional data about training from providers: label, intensity and source

Revision ID: 9b079dab9585
Revises: dc5ac28c4b94

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b079dab9585"
down_revision: Union[str, None] = "dc5ac28c4b94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workout_details", sa.Column("entry_source", sa.String(length=32), nullable=True))
    op.add_column("workout_details", sa.Column("intensity", sa.String(length=10), nullable=True))
    op.add_column("workout_details", sa.Column("label", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_details", "label")
    op.drop_column("workout_details", "intensity")
    op.drop_column("workout_details", "entry_source")
    # ### end Alembic commands ###
