"""workout_details_jsonb_update

Revision ID: 2d316787b998
Revises: 6b11080054a0

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d316787b998"
down_revision: Union[str, None] = "6b11080054a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workout_details", sa.Column("average_cadence", sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column("workout_details", sa.Column("segments", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("workout_details", sa.Column("hr_zones", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("workout_details", sa.Column("power_zones", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(
        "ix_workout_details_hr_zones_gin",
        "workout_details",
        ["hr_zones"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"hr_zones": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_workout_details_power_zones_gin",
        "workout_details",
        ["power_zones"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"power_zones": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_workout_details_segments_gin",
        "workout_details",
        ["segments"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"segments": "jsonb_path_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_workout_details_segments_gin",
        table_name="workout_details",
        postgresql_using="gin",
        postgresql_ops={"segments": "jsonb_path_ops"},
    )
    op.drop_index(
        "ix_workout_details_power_zones_gin",
        table_name="workout_details",
        postgresql_using="gin",
        postgresql_ops={"power_zones": "jsonb_path_ops"},
    )
    op.drop_index(
        "ix_workout_details_hr_zones_gin",
        table_name="workout_details",
        postgresql_using="gin",
        postgresql_ops={"hr_zones": "jsonb_path_ops"},
    )
    op.drop_column("workout_details", "power_zones")
    op.drop_column("workout_details", "hr_zones")
    op.drop_column("workout_details", "segments")
    op.drop_column("workout_details", "average_cadence")
    # ### end Alembic commands ###
