"""data_point_is_daily_total

Revision ID: 9f0940493a9b
Revises: 5aaff4551af6

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f0940493a9b"
down_revision: Union[str, None] = "5aaff4551af6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_point_series", sa.Column("is_daily_total", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_point_series", "is_daily_total")
    # ### end Alembic commands ###
