"""sync run tracking

Revision ID: 194bb4179f1f
Revises: b2c3d4e5f6a1

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "194bb4179f1f"
down_revision: Union[str, None] = "b2c3d4e5f6a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
