"""user_connection_status_index

Revision ID: dbb872a8b244
Revises: 4bd01c907050

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbb872a8b244"
down_revision: Union[str, None] = "4bd01c907050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_connection_user_id_status", "user_connection", ["user_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_connection_user_id_status", table_name="user_connection")
    # ### end Alembic commands ###
