"""meal details

Revision ID: 4b9d28928ca1
Revises: a18e054b6e0f

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b9d28928ca1"
down_revision: Union[str, None] = "a18e054b6e0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_details",
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("meal_type", sa.String(length=32), nullable=True),
        sa.Column("nutrients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["record_id"], ["event_record.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id"),
    )
    # ### end Alembic commands ###

    with op.get_context().autocommit_block():
        op.create_index(
            "ix_event_record_meal_source_external_id",
            "event_record",
            ["data_source_id", "external_id"],
            unique=True,
            postgresql_where=sa.text("category = 'meal'"),
            postgresql_concurrently=True,
        )
        op.create_index(
            "ix_event_record_source_time_tmp",
            "event_record",
            ["data_source_id", "start_datetime", "end_datetime"],
            unique=True,
            postgresql_where=sa.text("category <> 'meal'"),
            postgresql_concurrently=True,
        )
        op.drop_index("ix_event_record_source_time", table_name="event_record", postgresql_concurrently=True)
        op.execute("ALTER INDEX ix_event_record_source_time_tmp RENAME TO ix_event_record_source_time")


def downgrade() -> None:
    with op.get_context().autocommit_block():
        op.create_index(
            "ix_event_record_source_time_tmp",
            "event_record",
            ["data_source_id", "start_datetime", "end_datetime"],
            unique=True,
            postgresql_concurrently=True,
        )
        op.drop_index("ix_event_record_source_time", table_name="event_record", postgresql_concurrently=True)
        op.execute("ALTER INDEX ix_event_record_source_time_tmp RENAME TO ix_event_record_source_time")
        op.drop_index(
            "ix_event_record_meal_source_external_id", table_name="event_record", postgresql_concurrently=True
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meal_details")
    # ### end Alembic commands ###
