"""unified workout duration

Revision ID: 53b02f9426a2
Revises: eee09cc1f6d9

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b02f9426a2'
down_revision: Union[str, None] = 'eee09cc1f6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('source_name', sa.String(length=100), nullable=False))
    op.add_column('workout', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('workout', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('workout', 'endDate')
    op.drop_column('workout', 'sourceName')
    op.drop_column('workout', 'startDate')
    op.add_column('workoutstatistic', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('workoutstatistic', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('workoutstatistic', 'endDate')
    op.drop_column('workoutstatistic', 'sourceName')
    op.drop_column('workoutstatistic', 'startDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutstatistic', sa.Column('startDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workoutstatistic', sa.Column('sourceName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('workoutstatistic', sa.Column('endDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('workoutstatistic', 'end_datetime')
    op.drop_column('workoutstatistic', 'start_datetime')
    op.add_column('workout', sa.Column('startDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('sourceName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('endDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('workout', 'end_datetime')
    op.drop_column('workout', 'start_datetime')
    op.drop_column('workout', 'source_name')
    # ### end Alembic commands ###
