"""unified workout model

Revision ID: 80f94b41c69a
Revises: bb3d1c8232ec

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80f94b41c69a'
down_revision: Union[str, None] = 'bb3d1c8232ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop metadataentry first because it has FK to record
    op.drop_table('metadataentry')
    op.drop_table('record')
    op.drop_table('activeenergy')
    op.drop_table('heartratedata')
    op.drop_table('heartraterecovery')
    op.add_column('workoutstatistic', sa.Column('sourceName', sa.String(length=100), nullable=False))
    op.add_column('workoutstatistic', sa.Column('startDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('workoutstatistic', sa.Column('endDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('workoutstatistic', sa.Column('min', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('workoutstatistic', sa.Column('max', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('workoutstatistic', sa.Column('avg', sa.Numeric(precision=10, scale=3), nullable=True))
    op.alter_column('workoutstatistic', 'workout_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('workoutstatistic', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutstatistic', sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.alter_column('workoutstatistic', 'workout_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workoutstatistic', 'avg')
    op.drop_column('workoutstatistic', 'max')
    op.drop_column('workoutstatistic', 'min')
    op.drop_column('workoutstatistic', 'endDate')
    op.drop_column('workoutstatistic', 'startDate')
    op.drop_column('workoutstatistic', 'sourceName')
    op.create_table('heartraterecovery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('units', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('avg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('min', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('max', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('heartraterecovery_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('heartraterecovery_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('heartraterecovery_pkey'))
    )
    op.create_table('metadataentry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=15, scale=5), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name=op.f('metadataentry_record_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('metadataentry_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('metadataentry_pkey'))
    )
    op.create_table('heartratedata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('units', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('avg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('min', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('max', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('heartratedata_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('heartratedata_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('heartratedata_pkey'))
    )
    op.create_table('activeenergy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('units', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('qty', sa.NUMERIC(precision=15, scale=5), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('activeenergy_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('activeenergy_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activeenergy_pkey'))
    )
    op.create_table('record',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sourceName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('startDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('endDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=15, scale=5), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('record_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('record_pkey'))
    )
    # ### end Alembic commands ###