"""data_model_v2

Revision ID: 8df206a9988a
Revises: bbfb683a7c6c

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8df206a9988a'
down_revision: Union[str, None] = 'bbfb683a7c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_mapping_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('floors_climbed', sa.Integer(), nullable=True),
    sa.Column('active_calories_kcal', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_calories_kcal', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('active_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sedentary_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('intensity_minutes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['external_mapping_id'], ['external_device_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_mapping_id', 'date', name='uq_daily_activity_mapping_date')
    )
    op.create_table('daily_body_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_mapping_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('muscle_mass_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resting_heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('avg_hrv_rmssd_ms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blood_pressure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('basal_body_temperature_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['external_mapping_id'], ['external_device_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_mapping_id', 'date', name='uq_daily_body_mapping_date')
    )
    op.create_table('daily_recovery_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_mapping_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resting_heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('avg_hrv_rmssd_ms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_spo2_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recovery_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['external_mapping_id'], ['external_device_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_mapping_id', 'date', name='uq_daily_recovery_mapping_date')
    )
    op.create_table('meal_details',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=True),
    sa.Column('calories_kcal', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('carbohydrates_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('water_ml', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('measurement_details',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('measurement_type', sa.String(length=32), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.add_column('data_point_series', sa.Column('context', sa.String(length=32), nullable=True))
    op.add_column('data_point_series', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sleep_details', sa.Column('is_nap', sa.Boolean(), nullable=False))
    op.add_column('sleep_details', sa.Column('latency_seconds', sa.Integer(), nullable=True))
    op.add_column('workout_details', sa.Column('route', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workout_details', sa.Column('laps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_details', 'laps')
    op.drop_column('workout_details', 'route')
    op.drop_column('sleep_details', 'latency_seconds')
    op.drop_column('sleep_details', 'is_nap')
    op.drop_column('data_point_series', 'metadata_')
    op.drop_column('data_point_series', 'context')
    op.drop_table('measurement_details')
    op.drop_table('meal_details')
    op.drop_table('daily_recovery_summary')
    op.drop_table('daily_body_summary')
    op.drop_table('daily_activity_summary')
    # ### end Alembic commands ###
