"""init

Revision ID: 907ae6e7b787
Revises:

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "907ae6e7b787"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "developer",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_developer_email"), "developer", ["email"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apikey",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["developer.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("sourceName", sa.String(length=100), nullable=False),
        sa.Column("startDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("endDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Numeric(precision=15, scale=5), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("sourceName", sa.String(length=100), nullable=False),
        sa.Column("startDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("endDate", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activeenergy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("units", sa.String(length=50), nullable=True),
        sa.Column("qty", sa.Numeric(precision=15, scale=5), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workout.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "heartratedata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("units", sa.String(length=50), nullable=True),
        sa.Column("avg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("min", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("max", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workout.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "heartraterecovery",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("units", sa.String(length=50), nullable=True),
        sa.Column("avg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("min", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("max", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workout.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metadataentry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Numeric(precision=15, scale=5), nullable=False),
        sa.ForeignKeyConstraint(["record_id"], ["record.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workoutstatistic",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workout.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workoutstatistic")
    op.drop_table("metadataentry")
    op.drop_table("heartraterecovery")
    op.drop_table("heartratedata")
    op.drop_table("activeenergy")
    op.drop_table("workout")
    op.drop_table("record")
    op.drop_table("apikey")
    op.drop_table("user")
    op.drop_index(op.f("ix_developer_email"), table_name="developer")
    op.drop_table("developer")
    # ### end Alembic commands ###
