"""data model v2

Revision ID: 913acf4344b6
Revises: bbfb683a7c6c

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913acf4344b6'
down_revision: Union[str, None] = 'bbfb683a7c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_detail',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('sleep_total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_time_in_bed_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sleep_deep_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_rem_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_light_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_awake_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('workout_detail',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('heart_rate_min', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('heart_rate_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('max_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_watts', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_elevation_gain', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('average_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_watts', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('elev_high', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('elev_low', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.drop_table('sleep_details')
    op.drop_table('workout_details')
    op.add_column('data_point_series', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('data_point_series', sa.Column('external_device_mapping_id', sa.UUID(), nullable=False))
    op.add_column('data_point_series', sa.Column('series_type_definition_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_data_point_series_mapping_type_time'), table_name='data_point_series')
    op.create_index('idx_data_point_series_mapping_type_time', 'data_point_series', ['external_device_mapping_id', 'series_type_definition_id', 'recorded_at'], unique=False)
    op.drop_constraint(op.f('data_point_series_series_type_id_fkey'), 'data_point_series', type_='foreignkey')
    op.drop_constraint(op.f('data_point_series_external_mapping_id_fkey'), 'data_point_series', type_='foreignkey')
    op.create_foreign_key(None, 'data_point_series', 'series_type_definition', ['series_type_definition_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'data_point_series', 'external_device_mapping', ['external_device_mapping_id'], ['id'], ondelete='CASCADE')
    op.drop_column('data_point_series', 'series_type_id')
    op.drop_column('data_point_series', 'external_mapping_id')
    op.add_column('event_record', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('event_record', sa.Column('external_device_mapping_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_event_record_datetime_category'), 'event_record', type_='unique')
    op.drop_index(op.f('idx_event_record_mapping_category'), table_name='event_record')
    op.create_index('idx_event_record_mapping_category', 'event_record', ['external_device_mapping_id', 'category'], unique=False)
    op.drop_index(op.f('idx_event_record_mapping_time'), table_name='event_record')
    op.create_index('idx_event_record_mapping_time', 'event_record', ['external_device_mapping_id', 'start_datetime', 'end_datetime'], unique=False)
    op.create_unique_constraint('uq_event_record_datetime', 'event_record', ['external_device_mapping_id', 'start_datetime', 'end_datetime'])
    op.drop_constraint(op.f('event_record_external_mapping_id_fkey'), 'event_record', type_='foreignkey')
    op.create_foreign_key(None, 'event_record', 'external_device_mapping', ['external_device_mapping_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event_record', 'external_mapping_id')
    op.add_column('external_device_mapping', sa.Column('provider_name', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('uq_external_mapping_user_provider_device'), 'external_device_mapping', type_='unique')
    op.create_unique_constraint('uq_external_mapping_user_provider_device', 'external_device_mapping', ['user_id', 'provider_name', 'device_id'])
    op.drop_column('external_device_mapping', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_device_mapping', sa.Column('provider_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('uq_external_mapping_user_provider_device', 'external_device_mapping', type_='unique')
    op.create_unique_constraint(op.f('uq_external_mapping_user_provider_device'), 'external_device_mapping', ['user_id', 'provider_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('external_device_mapping', 'provider_name')
    op.add_column('event_record', sa.Column('external_mapping_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_record', type_='foreignkey')
    op.create_foreign_key(op.f('event_record_external_mapping_id_fkey'), 'event_record', 'external_device_mapping', ['external_mapping_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_event_record_datetime', 'event_record', type_='unique')
    op.drop_index('idx_event_record_mapping_time', table_name='event_record')
    op.create_index(op.f('idx_event_record_mapping_time'), 'event_record', ['external_mapping_id', 'start_datetime', 'end_datetime'], unique=False)
    op.drop_index('idx_event_record_mapping_category', table_name='event_record')
    op.create_index(op.f('idx_event_record_mapping_category'), 'event_record', ['external_mapping_id', 'category'], unique=False)
    op.create_unique_constraint(op.f('uq_event_record_datetime_category'), 'event_record', ['external_mapping_id', 'start_datetime', 'category'], postgresql_nulls_not_distinct=False)
    op.drop_column('event_record', 'external_device_mapping_id')
    op.drop_column('event_record', 'external_id')
    op.add_column('data_point_series', sa.Column('external_mapping_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('data_point_series', sa.Column('series_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'data_point_series', type_='foreignkey')
    op.drop_constraint(None, 'data_point_series', type_='foreignkey')
    op.create_foreign_key(op.f('data_point_series_external_mapping_id_fkey'), 'data_point_series', 'external_device_mapping', ['external_mapping_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('data_point_series_series_type_id_fkey'), 'data_point_series', 'series_type_definition', ['series_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_data_point_series_mapping_type_time', table_name='data_point_series')
    op.create_index(op.f('idx_data_point_series_mapping_type_time'), 'data_point_series', ['external_mapping_id', 'series_type_id', 'recorded_at'], unique=False)
    op.drop_column('data_point_series', 'series_type_definition_id')
    op.drop_column('data_point_series', 'external_device_mapping_id')
    op.drop_column('data_point_series', 'external_id')
    op.create_table('workout_details',
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('heart_rate_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heart_rate_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heart_rate_avg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('steps_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steps_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steps_avg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('steps_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_speed', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_watts', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('moving_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_elevation_gain', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('average_speed', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('average_watts', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('elev_high', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('elev_low', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], name=op.f('workout_details_record_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', name=op.f('workout_details_pkey'))
    )
    op.create_table('sleep_details',
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sleep_total_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_time_in_bed_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_efficiency_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('sleep_deep_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_rem_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_light_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_awake_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], name=op.f('sleep_details_record_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', name=op.f('sleep_details_pkey'))
    )
    op.drop_table('workout_detail')
    op.drop_table('sleep_detail')
    # ### end Alembic commands ###
