"""device_unique

Revision ID: a8e278aa8307
Revises: 2cf4fca4782d

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e278aa8307'
down_revision: Union[str, None] = '2cf4fca4782d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_data_source_identity', 'data_source', ['user_id', 'device_model', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_data_source_identity', 'data_source', type_='unique')
    # ### end Alembic commands ###
