"""update_developer

Revision ID: b76a97bf5a10
Revises: 78f7872254c8

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76a97bf5a10'
down_revision: Union[str, None] = '78f7872254c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer', sa.Column('username', sa.String(length=100), nullable=False))
    op.alter_column('developer', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('developer', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index(op.f('ix_developer_email'), table_name='developer')
    op.create_unique_constraint(None, 'developer', ['username'])
    op.create_unique_constraint(None, 'developer', ['email'])
    op.drop_column('developer', 'is_active')
    op.drop_column('developer', 'is_verified')
    op.drop_column('developer', 'is_superuser')
    op.drop_constraint(op.f('user_client_user_id_key'), 'user', type_='unique')
    op.drop_column('user', 'client_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_client_user_id_key'), 'user', ['client_user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('developer', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('developer', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('developer', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'developer', type_='unique')
    op.drop_constraint(None, 'developer', type_='unique')
    op.create_index(op.f('ix_developer_email'), 'developer', ['email'], unique=True)
    op.alter_column('developer', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               nullable=False)
    op.alter_column('developer', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.drop_column('developer', 'username')
    # ### end Alembic commands ###
