"""v3

Revision ID: c364bd6904cf
Revises: 913acf4344b6

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c364bd6904cf'
down_revision: Union[str, None] = '913acf4344b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_detail', sa.Column('energy_burned', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('workout_detail', sa.Column('distance', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_detail', 'distance')
    op.drop_column('workout_detail', 'energy_burned')
    # ### end Alembic commands ###
