"""device_and_software_device_fk

Revision ID: e34ddb1aaef9
Revises: 7a36d24b6c9c

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e34ddb1aaef9"
down_revision: Union[str, None] = "7a36d24b6c9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("device_software", "device_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("external_device_mapping", sa.Column("device_software_id", sa.UUID(), nullable=True))
    op.add_column("external_device_mapping", sa.Column("source", sa.String(length=50), nullable=False))
    op.alter_column(
        "external_device_mapping",
        "device_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="device_id::uuid",
    )
    op.drop_constraint(op.f("uq_external_mapping_user_provider_device"), "external_device_mapping", type_="unique")
    op.create_unique_constraint("uq_external_mapping_user_device", "external_device_mapping", ["user_id", "device_id"])
    op.create_foreign_key(None, "external_device_mapping", "device", ["device_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "external_device_mapping", "device_software", ["device_software_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("external_device_mapping", "provider_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_device_mapping",
        sa.Column("provider_name", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "external_device_mapping", type_="foreignkey")
    op.drop_constraint(None, "external_device_mapping", type_="foreignkey")
    op.drop_constraint("uq_external_mapping_user_device", "external_device_mapping", type_="unique")
    op.create_unique_constraint(
        op.f("uq_external_mapping_user_provider_device"),
        "external_device_mapping",
        ["user_id", "provider_name", "device_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "external_device_mapping",
        "device_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
        postgresql_using="device_id::varchar",
    )
    op.drop_column("external_device_mapping", "source")
    op.drop_column("external_device_mapping", "device_software_id")
    op.alter_column("device_software", "device_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
