"""developer_user_updates

Revision ID: eee09cc1f6d9
Revises: b76a97bf5a10

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee09cc1f6d9'
down_revision: Union[str, None] = 'b76a97bf5a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developer', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('developer_username_key'), 'developer', type_='unique')
    op.drop_column('developer', 'username')
    op.add_column('user', sa.Column('external_user_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['external_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'external_user_id')
    op.add_column('developer', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('developer_username_key'), 'developer', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('developer', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
