"""unified records

Revision ID: fbbab7b4040b
Revises: 53b02f9426a2

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbbab7b4040b'
down_revision: Union[str, None] = '53b02f9426a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_point_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('series_type', sa.Enum('steps', 'heart_rate', 'energy', name='seriestype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_point_series_device_type_time', 'data_point_series', ['device_id', 'series_type', 'recorded_at'], unique=False)
    op.create_table('body_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('body_fat_percentage', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('resting_heart_rate', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_record_time', 'event_record', ['user_id', 'start_datetime', 'end_datetime'], unique=False)
    op.create_index('idx_event_record_user_category', 'event_record', ['user_id', 'category'], unique=False)
    op.create_table('personal_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_record_detail',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('detail_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['event_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('sleep_details',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('sleep_total_duration_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sleep_time_in_bed_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sleep_efficiency_score', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sleep_deep_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sleep_rem_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sleep_light_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sleep_awake_minutes', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('workout_details',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('heart_rate_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('heart_rate_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('heart_rate_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('steps_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('steps_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('steps_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max_speed', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max_watts', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('moving_time_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_elevation_gain', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('average_speed', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('average_watts', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('elev_high', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('elev_low', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['event_record_detail.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.drop_table('workoutstatistic')
    op.drop_table('workout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workout_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_pkey'))
    )
    op.create_table('workoutstatistic',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('min', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('max', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('avg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workoutstatistic_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('workoutstatistic_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workoutstatistic_pkey'))
    )
    op.drop_table('workout_details')
    op.drop_table('sleep_details')
    op.drop_table('event_record_detail')
    op.drop_table('personal_record')
    op.drop_index('idx_event_record_user_category', table_name='event_record')
    op.drop_index('idx_event_record_time', table_name='event_record')
    op.drop_table('event_record')
    op.drop_table('body_state')
    op.drop_index('idx_data_point_series_device_type_time', table_name='data_point_series')
    op.drop_table('data_point_series')
    op.execute("DROP TYPE IF EXISTS seriestype")
    # ### end Alembic commands ###
